"""create pk05 table

Revision ID: fc9635fdf587
Revises: c687b8fee1c3
Create Date: 2026-02-27 16:43:09.545630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9635fdf587'
down_revision: Union[str, Sequence[str], None] = 'c687b8fee1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pk05',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_area', sa.String(length=100), nullable=False),
    sa.Column('deposit', sa.String(length=50), nullable=False),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('discharge_point', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('takt', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pk05_id'), 'pk05', ['id'], unique=False)
    op.create_table('pkmc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partnumber', sa.String(length=100), nullable=False),
    sa.Column('supply_area', sa.String(length=100), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=20), nullable=False),
    sa.Column('deposit_type', sa.String(length=100), nullable=False),
    sa.Column('deposit_position', sa.String(length=100), nullable=False),
    sa.Column('container', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('pack_standard', sa.String(length=50), nullable=True),
    sa.Column('qty_per_box', sa.Float(), nullable=False),
    sa.Column('qty_max_box', sa.Float(), nullable=False),
    sa.Column('total_theoretical_qty', sa.Float(), nullable=False),
    sa.Column('qty_for_restock', sa.Float(), nullable=False),
    sa.Column('rack', sa.String(length=10), nullable=False),
    sa.Column('lb_balance', sa.Float(), nullable=False),
    sa.Column('lb_balance_box', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pkmc_id'), 'pkmc', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pkmc_id'), table_name='pkmc')
    op.drop_table('pkmc')
    op.drop_index(op.f('ix_pk05_id'), table_name='pk05')
    op.drop_table('pk05')
    # ### end Alembic commands ###
